apiVersion: batch/v1
kind: Job
metadata:
  name: latents-nk
spec:
  parallelism: 5
  template:
    spec:
      priorityClassName: medium-priority
      restartPolicy: Never
      hostNetwork: true
      volumes: # Example volume mounting
      - name: textures # volume as referenced in the container
        hostPath: # host machine dir
          path: /mnt/scratch05/rendered_stimuli/image_textures 
      - name: external 
        hostPath:
          path: /mnt/dj-stor01 
      - name: project 
        hostPath:
          path: /mnt/scratch05/rendered_stimuli/renderstim 
      containers:
      - name: latents
        image: at-docker:5000/nkrender:latest
        workingDir: /data
        resources:
          requests:
            cpu: 10
            memory: 64Gi
        volumeMounts: # Container reference to volumes defined above
        - name: textures 
          mountPath: /mnt/image_textures
        - name: external
          mountPath: /external
        - name: project
          mountPath: /project
        env:
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: GITHUB_USERNAME
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: GITHUB_TOKEN
        command: ["/bin/bash"]
        args: ["-c", "python3 /project/renderstim/notebooks/generate.py"]

